spring:
  application:
    name: notificacao

  datasource:
    url: jdbc:postgresql://localhost:5432/notificacao
    username: ${GROUP_DB_USER:postgres}
    password: ${GROUP_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true